default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: 1695
  host: localhost
  pool: 5

development:
  <<: *default
  database: api_read_development

test:
  <<: *default
  database: api_read_test
